### ISSUE TITLE
An example of using tts-editor with TypeScript

### ISSUE THREAD

**Issue by ndelangen** [Sebaestschjin/tts-tools#5]
I'm interested in using your editor/tool, in combination with TypeScript, but am missing some instructions on how to use/set it up.

Do you have any examples anywhere? 🙏 

Thanks for this tool. ❤️

**Comment by ndelangen** [comment]
When I enable the `Tstl` feature, I get this error:
```
TypeError: Cannot read properties of undefined (reading '0')
```
..from the TTS editor output panel in VScode

**Comment by ndelangen** [comment]
After diggin around in the code a bit, I assumed a `tsconfig.json` was required, and adding this:
```
{
  "compilerOptions": {},
  "include": ["."],
  "exclude": [".tts"]
}
```
made the above error disappear, when enabling the `Tstl` feature.

Importing a ts file now results in this:
```
Could not resolve module 'ts.Global' required by '__root' at 2:0
```

So I'm likely misunderstand how to use the tool.

**Comment by Sebaestschjin** [comment]
Hi Norbert,

thansk for interest in the tool. :-)

Yeah, you need a working TSTL project first that includes the type definitions for TTS (see [https://www.npmjs.com/package/@typed-tabletop-simulator/declaration](here). I made a demo project with the setup of the `package.json` and `tsconfig.json` here: https://github.com/Sebaestschjin/typed-tabletop-simulator/tree/main/packages/demo

In the demo the generated Lua files will be created in a `lua` directory alongside the TS sources. The script in TTS would then use a `require(lua.index)` to include it.

This also works with pure TSTL and doesn't require the usage of the VS Code plugin. The plugin (or similar ones) is then only required to send the generated Lua scripts to TTS. The TSTL in this plugin basically simply runs TSTL on the whole project before sending the Lua scripts. However, in retrosprect, that kinda dumb. ^^" TSTL already offers a watch mode (like regular TS) which rebuilds files that where changed on the fly. So the typicall use-case would be to start TSTL in watch mode from a command line (the `dev` script in the demo project), develop in TS and on save the files will be converted to Lua. Then use the Save & Play functionality to send the Lua scripts to TTS.

The TSTL feature in tts-editor was added because I didn't know about watch mode before. I will remove it at some point from the plugin itself as using watch mode is way better than this approch. It's faster and doesn't hard-wire the used TSTL and TypeScript version to the plugin.

**Comment by ndelangen** [comment]
I got it..

That helps a whole lot!

I ended up adding this to my workspace settings:
```json
{
  "ttsEditor.includePath": "./lua",
  "ttsEditor.tstl.enable": false
}
```

And in my `Global.lua`:
```lua
require("index")
```
